import { NextRequest, NextResponse } from 'next/server';
import { PrismaClient, UserRole, UserStatus, HomeStatus, CareLevel } from '@prisma/client';
import bcrypt from 'bcryptjs';

export async function POST(request: NextRequest) {
  // Dev-only safety gate (allow override for e2e in built server)
  if (process.env.NODE_ENV !== 'development' && process.env['ALLOW_DEV_ENDPOINTS'] !== '1') {
    return NextResponse.json({ success: false, message: 'Only available in development mode' }, { status: 403 });
  }

  const prisma = new PrismaClient();
  try {
    const body = await request.json().catch(() => ({} as any));
    const email: string = (body.email as string) || 'operator+e2e@carelinkai.com';
    const rawPassword: string = (body.password as string) || 'Operator123!';
    const companyName: string = (body.companyName as string) || 'E2E Test Operator';

    const passwordHash = await bcrypt.hash(rawPassword, 10);

    // Upsert user as OPERATOR
    const user = await prisma.user.upsert({
      where: { email: email.toLowerCase() },
      update: {
        passwordHash,
        role: UserRole.OPERATOR,
        status: UserStatus.ACTIVE,
        emailVerified: new Date(),
        firstName: 'Op',
        lastName: 'Erator',
      },
      create: {
        email: email.toLowerCase(),
        passwordHash,
        role: UserRole.OPERATOR,
        status: UserStatus.ACTIVE,
        firstName: 'Op',
        lastName: 'Erator',
        emailVerified: new Date(),
      },
      select: { id: true }
    });

    // Ensure operator profile exists
    const operator = await prisma.operator.upsert({
      where: { userId: user.id },
      update: { companyName },
      create: { userId: user.id, companyName },
      select: { id: true }
    });

    // Ensure at least one home exists for this operator
    let home = await prisma.assistedLivingHome.findFirst({ where: { operatorId: operator.id } });
    if (!home) {
      const createdHome = await prisma.assistedLivingHome.create({
        data: {
          operatorId: operator.id,
          name: 'E2E Test Home',
          description: 'Autogenerated home for e2e compliance tests',
          status: HomeStatus.ACTIVE,
          careLevel: [CareLevel.ASSISTED],
          capacity: 10,
          currentOccupancy: 0,
          amenities: ['WiFi', 'Garden'],
        },
        select: { id: true, name: true }
      });
      home = createdHome as any;
    }

    return NextResponse.json({ success: true, userId: user.id, operatorId: operator.id, homeId: (home as any).id, email, password: rawPassword });
  } catch (e) {
    console.error('upsert-operator failed', e);
    return NextResponse.json({ success: false, message: 'Server error' }, { status: 500 });
  } finally {
    await prisma.$disconnect();
  }
}
