#!/usr/bin/env npx tsx
/**
 * scripts/archive-demo-test-homes.ts
 *
 * INCIDENT: ~11 demo/test homes leaked into the production directory and were ACTIVE,
 * ranking on family /search. This archives (status → INACTIVE) every ACTIVE home matching
 * ANY of the junk signatures below, and NOTHING else. The 144 real OH "CareLinkAI Directory
 * - Unclaimed Listings" homes are untouched.
 *
 * Match (ANY):
 *   (a) address.state != 'OH'  (or no address)        — all real directory homes are OH
 *   (b) operator.name ∈ { 'Sunshine Valley Care', 'CareLink Services Inc.' }
 *   (c) name OR description matches /e2e|autogenerated|deepagent|test home|compliance test/i
 *
 * SAFETY:
 *   - Dry-run by default. Prints every match (name · operator · state · reason).
 *   - --force REFUSES to write unless the match count equals --expect (default 11), so an
 *     unexpected match set (too many/few) aborts instead of mass-archiving. Override with
 *     --expect N only after reviewing the dry-run.
 *   - Only ever sets ACTIVE → INACTIVE; reversible.
 *
 * Usage:
 *   npx tsx scripts/archive-demo-test-homes.ts                 # DRY RUN
 *   npx tsx scripts/archive-demo-test-homes.ts --force         # apply (requires exactly 11 matches)
 *   npx tsx scripts/archive-demo-test-homes.ts --force --expect 11
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const JUNK_OPERATORS = new Set(['Sunshine Valley Care', 'CareLink Services Inc.']);
const JUNK_TEXT = /e2e|autogenerated|deepagent|test home|compliance test/i;

function argValue(flag: string): string | undefined {
  const i = process.argv.indexOf(flag);
  return i >= 0 ? process.argv[i + 1] : undefined;
}

async function main() {
  const isForce = process.argv.includes('--force');
  const dryRun = !isForce;
  const expect = parseInt(argValue('--expect') ?? '11', 10);

  console.log(dryRun ? '=== DRY RUN — no writes ===' : '=== LIVE — archiving demo/test homes ===');

  const homes = await prisma.assistedLivingHome.findMany({
    where: { status: 'ACTIVE' },
    select: {
      id: true,
      name: true,
      description: true,
      address: { select: { state: true } },
      operator: { select: { name: true, user: { select: { email: true } } } },
    },
    orderBy: { name: 'asc' },
  });

  const matches = homes
    .map((h) => {
      const state = h.address?.state ?? null;
      const opName = h.operator?.name ?? '';
      const reasons: string[] = [];
      if (state !== 'OH') reasons.push(`state=${state ?? 'none'}≠OH`);
      if (JUNK_OPERATORS.has(opName)) reasons.push(`operator="${opName}"`);
      if (JUNK_TEXT.test(h.name) || JUNK_TEXT.test(h.description ?? '')) reasons.push('test-text');
      return { h, state, opName, reasons };
    })
    .filter((m) => m.reasons.length > 0);

  console.log(`ACTIVE homes scanned: ${homes.length}  ·  matched junk: ${matches.length}\n`);
  for (const m of matches) {
    console.log(`  📦 "${m.h.name}"  [op="${m.opName}" · state=${m.state ?? 'none'}]`);
    console.log(`        reasons: ${m.reasons.join(', ')}`);
  }

  // Surface what we are NOT touching, for confidence.
  const realOhUnclaimed = homes.length - matches.length;
  console.log(`\nUntouched ACTIVE homes (real): ${realOhUnclaimed}`);

  console.log('\n─────────────────────────────────────────────');
  console.log(`${dryRun ? 'Would archive' : 'Archiving'}: ${matches.length}  (expected ${expect})`);
  console.log('─────────────────────────────────────────────');

  if (dryRun) {
    console.log('\nDRY RUN complete. Re-run with --force to write (aborts unless match count === --expect).');
    return;
  }

  if (matches.length !== expect) {
    console.error(`\n⛔ ABORT: matched ${matches.length} but expected ${expect}. Review the list and re-run with --expect ${matches.length} if it's correct.`);
    process.exit(1);
  }

  await prisma.assistedLivingHome.updateMany({
    where: { id: { in: matches.map((m) => m.h.id) } },
    data: { status: 'INACTIVE' },
  });
  console.log(`\n✅ Archived ${matches.length} demo/test homes → INACTIVE.`);
}

main()
  .catch((e) => { console.error('FATAL:', e); process.exit(1); })
  .finally(() => prisma.$disconnect());
